dist: bionic
language: node_js
node_js: 13

cache:
  yarn: true
  directories:
    - "node_modules"

stages:
  - name: install
  - name: lint
  - name: test
  - name: analysis
    if: branch = master



jobs:
  include:

  - stage: install
    script: npm install --package-lock

  - stage: test
    install:
      - npm ci
    script: npm test -- --coverage

  - stage: lint
    install:
      - npm ci
    script: npm lint -- -f json -o reports/eslint.json

  - stage: analysis
    script: npx gulp sonar
    name: sonar
    addons:
      sonarcloud:
        organization: danielvrog
        token: "$SONAR_TOKEN"