name: Lint, build and test

on: push

jobs:
  run-linters:
    name: Install and run lint
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:      
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 13.11

      # ESLint and Prettier must be in `package.json`
      - name: Install npm dependencies
        run: npm install

      - name: Run linters
        uses: samuelmeuli/lint-action@v1
        continue-on-error: false
        with:
          github_token: ${{ secrets.github_token }}
          # Enable linters
          eslint: true
          prettier: true

  install-and-test:
    name: Install and test
    needs: run-linters
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps: 
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install npm dependencies
        run: npm install

      - name: Run tests
        run: npm test
      
  sonarCloudTrigger:
    name: SonarCloud Trigger
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
